#!/bin/bash
###################################################################################
### Run SIMMER
###################################################################################

#SBATCH --job-name=simmer
#SBATCH --qos=regular
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jarcagniriv@unav.es
#SBATCH --cpus-per-task=3
#SBATCH --nodes=1
#SBATCH --mem=128G
#SBATCH -o results/logs/simmer_%j.out

set -euo pipefail

echo "==================================="
echo "===     Load the Packages       ==="
echo "==================================="
echo "$(date)"
module load Miniforge3/24.11.3-2

# NOTE: `conda activate` is unreliable in a non-interactive SLURM batch shell (silently stays on
# the module's base env, e.g. "ModuleNotFoundError: No module named 'pandas'") -- invoke the
# env's python binary directly instead.
PYTHON="/scratch/jarcagniriv/Envs/SIMMERenv/bin/python3"

# --- Case 1: KEGG ---
# SEED selects which seed's resampled KEGG-1.8K test set to use (data/Subsets/KEGG/seed_pools/seed$SEED/,
# generated by data/Subsets/KEGG/scripts/generate_seed_kegg_subset.py); defaults to the
# original fixed test set for backward compatibility.
SEED="${SEED:-42}"
if [ -d "data/Subsets/KEGG/seed_pools/seed${SEED}" ]; then
    KEGG_TEST_CSV="data/Subsets/KEGG/seed_pools/seed${SEED}/kegg_reactions_current_test.csv"
    KEGG_OUT_DIR="results/Case1/seed_runs/seed${SEED}/KEGG-1.8K"
else
    KEGG_TEST_CSV="data/Subsets/KEGG/kegg_reactions_current_test.csv"
    KEGG_OUT_DIR="results/Case1/KEGG-1.8K"
fi
mkdir -p "$KEGG_OUT_DIR"

$PYTHON methods/SIMMER/SIMMER_scripts/simmer_input.py \
    "$KEGG_TEST_CSV" \
    "methods/SIMMER/SIMMER_scripts/input/kegg_input_simmer_seed${SEED}.csv" \
    --reaction-id-col "Reaction ID" \
    --reaction-sep "<=>" \
    --substrates-col Equation \
    --sep "," \
    --smiles-col Isomeric_SMILES \
    --no-include-ec

# NOTE: methods/SIMMER/SIMMER_code/SIMMER/SIMMER_files/ (the KEGG/MetaCyc reference DB, e.g.
# chem_data/MC_rxn_fps.p) is an external dataset the README says to "import as indicated in the
# upstream repository" -- it was never actually set up in this checkout. Case 1 is skipped
# (not aborted) until that's resolved; Case 2 below builds its own self-contained reference DB
# from MetaNetX data and doesn't need it.
if [ -d methods/SIMMER/SIMMER_code/SIMMER/SIMMER_files ]; then
    mkdir -p "methods/SIMMER/SIMMER_scripts/output/ResultsKEGG_seed${SEED}"
    $PYTHON methods/SIMMER/SIMMER_code/SIMMER/SIMMER.py \
        -i methods/SIMMER/SIMMER_code/SIMMER/SIMMER_files \
        -o "methods/SIMMER/SIMMER_scripts/output/ResultsKEGG_seed${SEED}" \
        -q "methods/SIMMER/SIMMER_scripts/input/kegg_input_simmer_seed${SEED}.csv"

    $PYTHON methods/SIMMER/SIMMER_scripts/ec_predictions.py \
        --input_dir "methods/SIMMER/SIMMER_scripts/output/ResultsKEGG_seed${SEED}" \
        --output_file "$KEGG_OUT_DIR/SIMMER.csv"
else
    echo "SKIPPING SIMMER Case 1: SIMMER_files/ reference DB not present"
fi

# --- Case 2: MetaNetX ---
SKIP_METANETX="${SKIP_METANETX:-0}"
if [ "$SKIP_METANETX" != "1" ]; then
if [ -d "data/Splits-DBs/MetaNetX/seed_splits/seed${SEED}" ]; then
    METANETX_TRAIN="data/Splits-DBs/MetaNetX/seed_splits/seed${SEED}/train.tsv"
    METANETX_TEST="data/Splits-DBs/MetaNetX/seed_splits/seed${SEED}/test.tsv"
else
    METANETX_TRAIN="data/Splits-DBs/MetaNetX/train.tsv"
    METANETX_TEST="data/Splits-DBs/MetaNetX/test.tsv"
fi
SIMMER_METANETX_DB="methods/SIMMER/SIMMER_code/SIMMER/SIMMER_files_metanetx_seed${SEED}"
mkdir -p "$SIMMER_METANETX_DB/chem_data"

$PYTHON methods/SIMMER/SIMMER_scripts/simmer_input.py \
    "$METANETX_TEST" \
    "methods/SIMMER/SIMMER_scripts/input/metanetx_input_simmer_seed${SEED}.csv" \
    --reaction-id-col reaction_id \
    --substrates-col substrates_products \
    --smiles-col reaction_smiles \
    --no-include-ec

$PYTHON methods/SIMMER/SIMMER_scripts/simmer_input.py \
    "$METANETX_TRAIN" \
    "$SIMMER_METANETX_DB/chem_data/metanetx_reactions.csv" \
    --reaction-id-col reaction_id \
    --substrates-col substrates_products \
    --smiles-col reaction_smiles \
    --include-ec \
    --ec-col ec

$PYTHON methods/SIMMER/SIMMER_scripts/create_SIMMER_db.py --db_dir "$SIMMER_METANETX_DB"
$PYTHON methods/SIMMER/SIMMER_scripts/ec_permutations.py --db_dir "$SIMMER_METANETX_DB"

$PYTHON methods/SIMMER/SIMMER_code/SIMMER/SIMMER2.py \
    -i "$SIMMER_METANETX_DB" \
    -o "methods/SIMMER/SIMMER_scripts/output/ResultsMetaNetX_seed${SEED}" \
    -q "methods/SIMMER/SIMMER_scripts/input/metanetx_input_simmer_seed${SEED}.csv"

$PYTHON methods/SIMMER/SIMMER_scripts/ec_predictions.py \
    --input_dir "methods/SIMMER/SIMMER_scripts/output/ResultsMetaNetX_seed${SEED}" \
    --output_file results/Case2/results-DBs/MetaNetX/SIMMER.csv
else
    echo "SKIPPING Case 2 MetaNetX (SKIP_METANETX=1)"
fi

# --- Case 2: Rhea splits (Scaffold/Stratified), cofactors left in ---
# Generalizes run_SIMMER_rhea_baseline.sh (Stratified-only, no SEED support) into a SEED- and
# split-aware loop reusing the exact same underlying scripts (build_rhea_nocofactor_db.py /
# build_rhea_nocofactor_query.py / SIMMER2_generic.py / ec_predictions.py -- despite the
# "nocofactor" name, build_rhea_nocofactor_db.py builds the baseline/cofactors-in DB per its own
# header comment), pointed at each seed's data/Splits-Rhea/{Scaffold,Stratified}/seed_splits/
# seed${SEED}/{train,test}.tsv instead of the un-seeded Stratified-only baseline files.
# These raw Rhea files use uppercase REACTION_ID/REACTION_SMILES/EC_NUMBER columns directly --
# no lowercase-renamed prepared/ copy needed here (unlike BEC-Pred/Theia above).
# RHEA_SPLIT selects which split(s) to run (space-separated "Scaffold"/"Stratified"); defaults to
# both if unset.
RHEA_SPLITS="${RHEA_SPLIT:-Scaffold Stratified}"
for SPLIT in $RHEA_SPLITS; do
    SPLIT_LC=$(echo "$SPLIT" | tr '[:upper:]' '[:lower:]')
    RHEA_SEED_DIR="data/Splits-Rhea/${SPLIT}/seed_splits/seed${SEED}"
    if [ ! -d "$RHEA_SEED_DIR" ]; then
        echo "SKIPPING SIMMER Rhea $SPLIT seed $SEED: '$RHEA_SEED_DIR' not found"
        continue
    fi
    RHEA_TRAIN="$RHEA_SEED_DIR/train.tsv"
    RHEA_TEST="$RHEA_SEED_DIR/test.tsv"
    SIMMER_RHEA_DB="methods/SIMMER/SIMMER_code/SIMMER/SIMMER_files_rhea_${SPLIT_LC}_seed${SEED}"
    RHEA_SIMMER_OUT_DIR="methods/SIMMER/SIMMER_scripts/output/ResultsRhea${SPLIT}Seed${SEED}"
    RHEA_QUERY_CSV="methods/SIMMER/SIMMER_scripts/input/rhea_${SPLIT_LC}_seed${SEED}_query.csv"
    RESULTS_SEED_DIR="results/Case2/results-splits/seed_runs/seed${SEED}/${SPLIT}"
    mkdir -p "$RHEA_SIMMER_OUT_DIR" "$RESULTS_SEED_DIR"

    $PYTHON methods/SIMMER/SIMMER_scripts/build_rhea_nocofactor_db.py \
        --input "$RHEA_TRAIN" \
        --output-dir "$SIMMER_RHEA_DB"

    $PYTHON methods/SIMMER/SIMMER_scripts/build_rhea_nocofactor_query.py \
        --input "$RHEA_TEST" \
        --output-query "$RHEA_QUERY_CSV" \
        --output-truth "$RESULTS_SEED_DIR/${SPLIT}_ground_truth.csv"

    $PYTHON methods/SIMMER/SIMMER_code/SIMMER/SIMMER2_generic.py \
        -i "$SIMMER_RHEA_DB" \
        -o "$RHEA_SIMMER_OUT_DIR" \
        -q "$RHEA_QUERY_CSV"

    $PYTHON methods/SIMMER/SIMMER_scripts/ec_predictions.py \
        --input_dir "$RHEA_SIMMER_OUT_DIR" \
        --output_file "$RESULTS_SEED_DIR/SIMMER.csv"
done

# --- Case Study: drugs --- (also needs SIMMER_files/, see NOTE above; skipped if absent)
SKIP_CASESTUDY="${SKIP_CASESTUDY:-0}"
if [ "$SKIP_CASESTUDY" = "1" ]; then
    echo "SKIPPING SIMMER Case Study (SKIP_CASESTUDY=1)"
elif [ -d methods/SIMMER/SIMMER_code/SIMMER/SIMMER_files ]; then
    $PYTHON methods/SIMMER/SIMMER_scripts/simmer_input.py \
        data/Drugs/drug_smiles_updated.csv \
        methods/SIMMER/SIMMER_scripts/input/simmer_drugs_input.csv \
        --reaction-id-col drug \
        --substrates-col right_comp \
        --sep "," \
        --smiles-col reaction_smiles \
        --no-include-ec

    mkdir -p methods/SIMMER/SIMMER_scripts/output/ResultsDrugs
    $PYTHON methods/SIMMER/SIMMER_code/SIMMER/SIMMER.py \
        -i methods/SIMMER/SIMMER_code/SIMMER/SIMMER_files \
        -o methods/SIMMER/SIMMER_scripts/output/ResultsDrugs \
        -q methods/SIMMER/SIMMER_scripts/input/simmer_drugs_input.csv

    $PYTHON methods/SIMMER/SIMMER_scripts/ec_predictions.py \
        --input_dir methods/SIMMER/SIMMER_scripts/output/ResultsDrugs \
        --output_file results/CaseStudy/results/SIMMER.csv
else
    echo "SKIPPING SIMMER Case Study: SIMMER_files/ reference DB not present"
fi
